image: gengjiawen/node-build

tasks:
  - init: yarn && node-gyp --debug configure rebuild

vscode:
  extensions:
    - vadimcn.vscode-lldb@1.6.0:TlOEY068MsoPv6/D7EZlLg==

# lldb init
# command script import /home/gitpod/lldb_commands.py