tasks:
  - init: |
      nvm alias default v16.16.0
      nvm install node
      npm i -g @gengjiawen/node-dev
      node-dev setuplldb && yarn
    command: |
      node-gyp --debug configure rebuild

vscode:
  extensions:
    - vadimcn.vscode-lldb

# lldb init
# command script import /home/gitpod/lldb_commands.py
